### PR TITLE
Use Trove4J dependency instead of repackaging it.

### PR DESCRIPTION
**Pull request by pyricau**
This separates out Trove4j from HAHA since Trove4j is available under LGPL 2.1 and HAHA is available under Apache 2.

HAHA is released to Maven Central as v 2.0.4 .

### CODE REVIEW

**Comment by robeden** [comment]
The annoying thing that happened here is that the Trove version used to be shaded along with the rest of the bits from the Android SDK. Now they aren't so they collide with other versions of Trove. This can obviously be worked around by users doing their own shading, but it would be nice not to have to deal with it since the Android SDK bits are still shaded.

**Comment by pyricau** [comment]
Good point, sorry about that.

Unfortunately, I don't have a great answer there. The prior state wasn't great from a license perspective, and I got strong feedback that it needed to change :) . I wish perflib just got rid of the Trove4j dependency.

**Comment by robeden** [comment]
>  I wish perflib just got rid of the Trove4j dependency.

Yeah, or used an official version of Trove. 🙄 (Disclaimer: I've been the main Trove maintainer for years.)


At one point I started working on the skimmed down rewrite of perflib that was a bit more optimal for this type of leak analysis. Maybe that needs to be pulled back off the neglected project pile...

**Comment by pyricau** [comment]
Sent you an email :)

**Pull request merged**
