### PR TITLE
Formatting all the code

### PR DESCRIPTION
**Pull request by pyricau**
Looks like we'll need to do at least a few changes in that repo, so let's reformat it all, to make our life easier.

Git history be lost...

### CODE REVIEW

**Comment by swankjesse** [comment]
Any chance that there will be upstream changes we'll want to incorporate? If so it's probably a simpler move to just adjust your IDE to support a code style specific to this project.

**Comment by swankjesse** [comment]
LGTM

**Comment by pyricau** [comment]
@swankjesse that ship has sailed. The first fork of MAT was done in 2010, and I couldn't find which commit it had derived from. If we want to rebase on upstream, we need to throw all this and rebuild a clean headless version of MAT. That's an effort I'm not willing to do any time soon.

**Comment by pyricau** [comment]
Which is also why I'm going crazy on format here: so that subsequent changes are clear.

**Comment by pyricau** [comment]
To be honest, I'm going to hate every single change I do on this repo. The less I do here, the better I feel.

**Pull request merged**
